dist: xenial
sudo: false
language: cpp

os:
  - osx

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc6 {apt: {packages: [g++-6] , sources: [ubuntu-toolchain-r-test]}}
      env: BUILD_TYPE=Coverage COMPILER_VER=6
    - os: linux
      compiler: gcc
      addons: {apt: {packages: [g++-6,doxygen] , sources: [ubuntu-toolchain-r-test]}}
      env: BUILD_TYPE=Release COMPILER_VER=6 GEN_DOC=TRUE
    - os: linux # Use 3.8 since 3.9 is broken on trusty when using ASAN
      compiler: clang
      addons: &clang38 {apt: {packages: [clang-3.8,libstdc++-6-dev] , sources: [ubuntu-toolchain-r-test]}}
      env: BUILD_TYPE=Debug COMPILER_VER=3.8 USE_ASAN=1
    - os: linux
      compiler: clang
      addons: *clang38
      env: BUILD_TYPE=Debug COMPILER_VER=3.8 USE_UBSAN=1
    - os: linux
      compiler: clang
      addons: &clang39 {apt: {packages: [clang-3.9,libstdc++-6-dev] , sources: [ubuntu-toolchain-r-test,llvm-toolchain-trusty-3.9]}}
      env: BUILD_TYPE=Debug COMPILER_VER=3.9
    - os: linux
      compiler: clang
      addons: *clang39
      env: BUILD_TYPE=Release COMPILER_VER=3.9
    - os: linux
      compiler: clang
      addons: &clang4 {apt: {packages: [clang-4.0,libstdc++-6-dev] , sources: [ubuntu-toolchain-r-test,llvm-toolchain-trusty-4.0]}}
      env: BUILD_TYPE=Debug COMPILER_VER=4.0 USE_ASAN=1 LSAN_OPTIONS=verbosity=1:log_threads=1
      sudo: required
    - os: linux
      compiler: clang
      addons: *clang4
      env: BUILD_TYPE=Release COMPILER_VER=4.0 USE_UBSAN=1
    - os: linux
      compiler: clang
      addons: &clang6 {apt: {packages: [clang-6.0,libstdc++-6-dev] , sources: [ubuntu-toolchain-r-test]}}
      env: BUILD_TYPE=Debug COMPILER_VER=6.0 USE_ASAN=1 LSAN_OPTIONS=verbosity=1:log_threads=1
      sudo: required
    - os: linux
      compiler: clang
      addons: *clang6
      env: BUILD_TYPE=Release COMPILER_VER=6.0 USE_UBSAN=1

cache:
  directories:
    - $HOME/.local

install:
  - if [[ "${COMPILER_VER}" != "" ]]; then export CXX=${CXX}-${COMPILER_VER}; fi
  - if [[ "${COMPILER_VER}" != "" ]]; then export CC=${CC}-${COMPILER_VER}; fi
  - if [[ "${COMPILER_VER}" != "" ]]; then export GCOV=gcov-${COMPILER_VER}; fi
  - if [[ "${USE_ASAN}" == "1" ]]; then export CXXFLAGS="-fsanitize=address -fno-omit-frame-pointer"; fi
  - if [[ "${USE_UBSAN}" == "1" ]]; then export CXXFLAGS="-fsanitize=undefined -fno-omit-frame-pointer"; fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      mkdir -p $HOME/.local

      CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.16.4/cmake-3.16.4-Linux-x86_64.tar.gz"
      if [ ! -e $HOME/.local/bin/cmake ]; then
          echo "CMake not found in the cache, get and extract it..."
          travis_retry curl -L ${CMAKE_URL} \
              | tar -xz -C $HOME/.local --strip-components=1
      else
          echo "Using cached CMake"
      fi
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update && brew upgrade cmake
    fi

script:
  - cmake --version
  - ${CXX} --version
  - echo CXXFLAGS=${CXXFLAGS}
  - |
    if [[ "$BUILD_TYPE" == "Coverage" ]]; then
      ctest -S cmake/CI.CTestScript.cmake --output-on-failure -VV -DCTEST_SITE=Travis -DCTEST_BUILD_NAME="${TRAVIS_OS_NAME}-$BUILD_TYPE"
    else
      mkdir build && cd build && \
      cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && \
      make -j4 && \
      ctest -VV .
    fi
  - |
    if [[ "$GEN_DOC" == "TRUE" ]]; then
      cmake --build . --target doc
    fi

after_success:
  - |
    if [[ "$BUILD_TYPE" == "Coverage" ]]; then
      bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
    fi

# See the documentation for more details : https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN #You will need to add your (ENCRYPTED if set in the .travis.yml) GH token as environment variable of your project
  keep-history: true
  on:
    branch: master
    condition: $GEN_DOC = TRUE
  local-dir: build/html
